apiVersion: v1
kind: Service
metadata:
  name: knox-ui
  namespace: knox
  labels:
    app: knox-ui
    app.kubernetes.io/part-of: knox-platform
spec:
  selector:
    app: knox-ui
  ports:
    - port: 3000
      targetPort: 3000
      name: http

